<?php

use PressLoft\Affiliate\Model\Affiliate;

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<script>
    require(
        [
            'jquery'
        ],
        function ($) {
            "use strict";
            const tokenName = '<?= /* @noEscape */ Affiliate::TOKEN ?>';
            const urlParams = new URLSearchParams(window.location.search);
            if (urlParams) {
                const tokenValue = urlParams.get(tokenName);
                if (tokenValue) {
                    sendToken(tokenValue);
                }
            }

            function sendToken(token) {
                $.ajax({
                    url: '<?= $escaper->escapeUrl($block->getUrl('plaffiliate/token/validate')); ?>',
                    data: {<?= /* @noEscape */ Affiliate::TOKEN ?>: token},
                    dataType: "json"
                });
            }
        }
    );
</script>
